### ISSUE TITLE
Provide wheels for Raspberry Pi with piwheels

### ISSUE THREAD

**Issue by filips123** [wasmerio/wasmer-python#107]
### Motivation

Wheels are only provided for classic 64-bit Linux systems. This means that is is currently not possible to easily use Python Wasmer library on Raspberry Pi, as well as other ARM-based systems.

### Proposed solution

You should provide wheels for Raspberry Pi. However, you shouldn't publish them on PyPI, as Raspberry Pi `armv7l` can be uncompatible with other ARM-based systems. Instead, they should be published on [piwheels](https://www.piwheels.org/) which is a Python package repository providing Arm platform wheels specifically for the Raspberry Pi.

Normally, wheels are automatically built and published by piwheels servers, but as this library requires extra building steps (and actually even doesn't publish source code to PyPI), this doesn't work.

You will probably need to contact @bennuttall or @waveform80 to set up build dependencies on piwheels servers and provide instructions for building library.

**Comment by Hywan** [comment]
@syrusakbary Can you help here?

**Comment by syrusakbary** [comment]
Thanks for creating the issue. It is the first time I hear of piwheels but I'll be super happy to give it a try.

Hi @bennuttall, @waveform80, could you provide some info on how to get the build system work for the Wasmer library case?

**Comment by Hywan** [comment]
I've dust an old RPi down. I'm trying to compile `python-ext-wasm` on it. If that works great, then I'll try to cross-compile from Ubuntu with Github Actions to ARMv6 (RPi 1 A/B and Zero), v7 (RPi 2 B) and v8 (RPi 2/3/4 A/B). So far, I've been able to cross compile from macOS to ARMv7, it should easier from Ubuntu I think (with https://github.com/raspberrypi/tools).

**Comment by Hywan** [comment]
We can't publish on piwheels because it only supports 32bits binary wheel. Ours are 64bits binary wheels. I'm closing this. Discussion follows at #469.
