### ISSUE TITLE
is this lib only support rust's wasm?

### ISSUE THREAD

**Issue by sonygod** [wasmerio/wasmer-python#121]
### Summary

is this lib only support rust's wasm?

I can't test wasm build by cpp.

### Additional details

index.cc

    
    #include <emscripten/bind.h>

    using namespace emscripten;

    int add(int x,int y){
        return x+y;
    } 

    EMSCRIPTEN_BINDINGS(module){
        function("add",&add);
    }

and command to build

   emcc index.cc --std=c++11 --bind -s WASM=1

and load into python

 
    from wasmer import Instance

    # Get the Wasm module as bytes.
    wasm_bytes = open('index.wasm', 'rb').read()

    # Instantiate the Wasm module.
    instance = Instance(wasm_bytes)

    # Call a function on it.
    result = instance.exports.add(1, 2)

//not work .

and use Module also not work too.

**Comment by Mec-iS** [comment]
Hi,
The library should work with any valid Wasm binary.
Can you be more precise about what is not working?
what is the outcome if you try `print(result)`? Did you get any error?

**Comment by Hywan** [comment]
I bet we need to setup all Emscripten imports. It's ready, we just need to do it.

**Comment by Hywan** [comment]
#122 contains a C to Wasm example, compiled with wasmcc (check the https://github.com/wasienv/wasienv project).

**Comment by sonygod** [comment]
@Mec-iS  @Hywan 
[test.zip](https://github.com/wasmerio/python-ext-wasm/files/4132306/test.zip)
![image](https://user-images.githubusercontent.com/748320/73421943-621ac900-4362-11ea-84c4-c6e50fcac502.png)

**Comment by syrusakbary** [comment]
Hi @sonygod it seems you are trying to run a webassembly file generated with Emscripten, for which the imports are not generated in the Python side.

Can you try it generating it wis wasienv?

**Comment by sonygod** [comment]
I have not try wasienv before.. current  version is not support Emscripten?

**Comment by Hywan** [comment]
> current version is not support Emscripten?

What do you mean?

**Comment by filips123** [comment]
Will Emscripten be supported in the future?

**Comment by Hywan** [comment]
Yes! I think it will come in the next release.

**Comment by Hywan** [comment]
emscripten now supports WASI, and with #167, we also support WASI. Maybe it's the missing link. I can also add support for emscripten if needed.

**Comment by vinayak-mehta** [comment]
@Hywan emscripten support would be awesome!

**Comment by Hywan** [comment]
We support WASI now :-).

**Comment by Hywan** [comment]
See https://github.com/wasmerio/wasmer-python/issues/470 to discuss about emscripten if it's a strong requirement.
