### ISSUE TITLE
panicked at 'index out of bounds' with emscriptien, malloc, zstd

### ISSUE THREAD

**Issue by dholth** [wasmerio/wasmer-python#154]
https://github.com/dholth/zstdpy/blob/master/streaming_decompression.py#L60

Suggestion: put a warning against emscripten at the top of the docs.

Will try with wasienv.

You are welcome to take this as a more complicated example (if it starts working)

**Comment by dholth** [comment]
I've figured out that wasi-sdk exists, but getting the -unknown-unknown target going is a stretch.

**Comment by Hywan** [comment]
Emscripten supports is coming with host functions, thanks for your patience!

**Comment by Hywan** [comment]
I advice you to use [WASI](https://wasmerio.github.io/wasmer-python/api/wasi/index.html) with [`wasienv`](https://github.com/wasienv/wasienv/) to compile your C/C++ code. If you want to discuss about emscripten strictly, see #470.
