### ISSUE TITLE
Transfering strings (and other high level objects) between host and module

### ISSUE THREAD

**Issue by filips123** [wasmerio/wasmer-python#184]
### Motivation

Currently, Wasmer supports viewing raw memory and accessing functions with numeric parameters and returns. However, it is not (easily) possible to transfer/access strings, arrays/lists/dictionaries and other high level objects.

### Proposed solution

Ideally, WebAssembly specs should be updated to support strings and other high level objects :)

More realistic approach is to provide some wrapper functions both to host and WebAssembly module to easily store strings and other objects into memory using currently supported data types and then later easily view/access them.

Some other tools (which are mostly for JS in browsers) already provide similar things. Some of them are [Bindgen](https://medium.com/wasm/strings-in-webassembly-wasm-57a05c1ea333), [Nbind and Embind](https://stackoverflow.com/questions/41353389/how-can-i-return-a-javascript-string-from-a-webassembly-function), there are also [some JS functions for this](https://dev.to/adam_cyclones/wasm-strings-with-ease-13ec) and [Emscripten also provides some high level wrappers](https://emscripten.org/docs/api_reference/preamble.js.html). You can get others if you just search something like "webassembly strings." Wasmer's implementation of this could be compatible with some of existing implementations for JS to make it easier to write such modules.

### Alternatives

It is already [possible](https://github.com/wasmerio/python-ext-wasm#lets-see-in-action) that function returns pointer to a string and you then manually view memory and assemble the string, but this is not really very practical.

**Comment by Hywan** [comment]
The [WebAssembly interface types (WIT) proposal](https://github.com/WebAssembly/interface-types) will solve this problem. We already have a crate to implement it, [`wasmer-interface-types`](https://github.com/wasmerio/interface-types), but none of them is stable yet. Be sure that as soon as it's stable, it will quickly be implemented in the Python embedding. For the moment, I'm closing this issue :-).
