### ISSUE TITLE
No Windows wheels on PyPI?

### ISSUE THREAD

**Issue by whitequark** [wasmerio/wasmer-python#196]
The master branch README says there are wheels on PyPI. But I [look at PyPI](https://pypi.org/project/wasmer/#files) and it looks like there aren't any. What gives?

**Comment by Hywan** [comment]
The next release will have wheels for Windows. I want to add one or two more features before releasing the next version.

**Comment by Hywan** [comment]
Alternatively, you can use the beta of the next version, https://github.com/wasmerio/python-ext-wasm/releases, if it's urgent. Or you can compile with `just build` on Windows to get it work. I hope it helps!

The release will come very soon.

**Comment by whitequark** [comment]
No rush! I was just wondering if that's another mistake in README.

**Comment by Hywan** [comment]
I did that to solve #29 (closed by #100), but it still lands on the `master`.

**Comment by Hywan** [comment]
Next release will provide them. Closing this issue.
