### ISSUE TITLE
After installing the beta version with Windows support, still getting import error

### ISSUE THREAD

**Issue by analogaio** [wasmerio/wasmer-python#209]
As the title says, I installed the beta version 0.4.2 and yet I'm still getting `ImportError: Wasmer is not available on this system` .
It's possible that I couldn't installed it wrong but I did `pip install  wasmer-0.4.2_beta_11-cp36-none-win_amd64` and it said that it installed correctly. Anyone able to help me out?

**Comment by Hywan** [comment]
What version of Windows do you have?

**Comment by hyperesellto** [comment]
> What version of Windows do you have?

Latest version of Windows 10

**Comment by Hywan** [comment]
Gimme time to grab a copy of Windows.

**Comment by Hywan** [comment]
A fully rewritten version of the `wasmer` package has been written and lands in `master`. Let's see how it goes with the incoming 1.0.0alpha version.

**Comment by Hywan** [comment]
The 1.0.0 version has been released. You have [Windows wheels on pypi](https://pypi.org/project/wasmer/). Please try with this version, and report to us any issue. I'm closing the issue, but feel free to re-open if you have any kind of problems with installations on Windows!
