### ISSUE TITLE
How to install compiler packages?

### ISSUE THREAD

**Issue by vinayak-mehta** [wasmerio/wasmer-python#253]
The compiler packages mentioned in the README aren't available on PyPI yet. But I was able to set up wasmer-python using the development instructions and run the examples, and I see that the examples don't require any of the compiler packages.

Will compiler packages be available with the next wasmer-python release?

Thank you for your work on wasmer!

**Comment by Hywan** [comment]
The release is coming next week. We need to fork https://github.com/actions/upload-release-asset to provide more features. I'm working on it right now :-).

**Comment by vinayak-mehta** [comment]
Thanks :+1:

**Comment by syrusakbary** [comment]
We did finally published the packages.
You can now install cranelift and singlepass compilers (llvm will be published soon).

```bash
pip install wasmer_compiler_singlepass==1.0.0a3
pip install wasmer_compiler_cranelift==1.0.0a3
```

Closing the issue :)

**Comment by vinayak-mehta** [comment]
Thank you!
