### ISSUE TITLE
How to set the buffer allocated by WASM. from Python?

### ISSUE THREAD

**Issue by chaosprint** [wasmerio/wasmer-python#306]
some pseudo code:
```
string_to_set = np.frombuffer(b"hello", dtype=uint8)
str_len = len(string_to_set)
ptr= instance.exports.alloc(str_len )


# this is what can be done in JS
arr= UInt8Array.new(instance.exports.memory.buffer(), prt, str_len)
arr.set(string_to_set )
```

OK, I managed to make it like this:
```
for i, u in enumerate(string_to_set):
    instance.exports.memory.uint8_view()[i] = int(u)
```

Still, I think this should be included in the `example_memory.py`

**Comment by Hywan** [comment]
Hello,

I'm not sure I understood your issue. You can do that:

```python
view = instance.exports.memory.uint8_view()
view[i:i + str_len] = str
```

Also, calling `instance.exports` creates a new `Exports` object. Calling `exports.memory` creates a new `Memory` object. Calling `memory.uint8_view()` creates a new `Uint8Array`. You should not do that in a loop, as it can start being expensive on the memory side.
