### ISSUE TITLE
Register as Python `Importer`

### ISSUE THREAD

**Issue by piranna** [wasmerio/wasmer-python#37]
### Motivation

Way to use this project is simple, but by micking Javascipt API, it's not pythonic nor transparent to users.

### Proposed solution

Implement [Python `Importers` protocol](https://docs.python.org/3/reference/import.html#finders-and-loaders) so WebAssembly modules can be imported in Python code as if they were Python modules, with plain `from blah import foo` statements.

**Comment by piranna** [comment]
With that, ideally after registering the importer, the example code of `Readme.md` file would be left as this:

```python
from simple.exports import sum

result = sum(5, 37)

print(result) # 42!
```

All the WebAssembly importing and initialization is done under the hoods, and the Python user can't be able to differenciate if it's a Python or WebAssembly module, the same that happens with Python native (C compiled) modules except for the `exports` or `memory` attributes.

**Comment by Hywan** [comment]
I like the idea. I really like it.

So a complete example would be written:

```python
from wasmer import Instance

simple = Instance(open('simple.wasm', 'rb').read())

from simple.exports import sum

result = sum(5, 37)
```

That's an interesting approach. It's more verbose, but more Pythonic. cc @Mec-iS @syrusakbary 

We can also imagine this API:

```python
simple = Instance(…)

from simple import sum

result = sum(5, 37)
```

Thoughts?

**Comment by Mec-iS** [comment]
I do also like the idea! That is more or less what I was thinking about when I mentioned [here](https://github.com/wasmerio/python-ext-wasm/pull/36#issuecomment-491740351) that we should treat the exported functions as a Python module/namespace.

If it can help, modules (that are imported via `import module`) can be created programmatically via the `sys` package in the stdlib, for [example](https://stackoverflow.com/questions/2315044/how-to-generate-a-module-object-from-a-code-object-in-python).

**Comment by piranna** [comment]
```js
simple = Instance(…)

from simple import sum

result = sum(5, 37)
```

That was my original idea, but having `exports` and `memory`, this last one makes it a bit more complicated... :-/ Other thing is if both gets merged, it's difficult there could be some module that exports at the same time a memory and a `exports.memory` entry...


> I do also like the idea! That is more or less what I was thinking about when I mentioned [here](https://github.com/wasmerio/python-ext-wasm/pull/36#issuecomment-491740351) that we should treat the exported functions as a Python module/namespace.

Yes, Python namespaces is my idea behing this :-)

> If it can help, modules (that are imported via `import module`) can be created programmatically via the `sys` package in the stdlib, for [example](https://stackoverflow.com/questions/2315044/how-to-generate-a-module-object-from-a-code-object-in-python).

Definitely it does :-D

**Comment by Mec-iS** [comment]
The first implementation that I run into when trying to achieve a cleaner Python interface is something that should work like:
```python
from wasmer import Load  # or LoadInstance

module = Load(BYTES)

from module import func
...
```
This way the "factory" `Load` can create an instance and a namespace, and return a namespace/module. The namespace/module is added as a sub-module to `wasmer` module

Some random ideas taken form `pyo3` doc (_just pseudo-Rust_):
1. `fn wasmer` shall declare a sub-module with: 
```rust
    ...
    module.add_wrapped(wrap_pymodule!(namespace(&instance)));
    ...
```
2. `fn namespace` (of `fn module`) could be defined as:
```rust
#[pymodule]
fn namespace(_py: Python, module: &PyModule, instance: &Instance) -> PyResult<()> {
    for f in instance.exports { 
       module.add_function(f)
    }
}
```
or by defining it as a [pyo3::types::PyModule](https://pyo3.rs/master/doc/pyo3/types/struct.PyModule.html).

I don't know if it is feasible but it is probably the most `pyo3`-onic solution without changing how Instance is currently declared.

Doing something like as proposed:
> ```
> simple = Instance(…)
>
> from simple import sum
>
> result = sum(5, 37)
> ```
will need a re-purposing/refactoring of `Instance` into a [pyo3::types::PyModule](https://pyo3.rs/master/doc/pyo3/types/struct.PyModule.html).

What do you think?

**Comment by piranna** [comment]
> ```python
> from wasmer import Load  # or LoadInstance
> 
> module = Load(BYTES)
> 
> from module import func
> ...
> ```

Are these two files? What's `BYTES`?


> This way the "factory" `Load` can create an instance and a namespace, and return a namespace/module. The namespace/module is added as a sub-module to `wasmer` module

Dynamically added sub-modules?


> Doing something like as proposed:
> 
> > ```
> > simple = Instance(…)
> > 
> > from simple import sum
> > 
> > result = sum(5, 37)
> > ```
> 
> will need a re-purposing/refactoring of `Instance` into a [pyo3::types::PyModule](https://pyo3.rs/master/doc/pyo3/types/struct.PyModule.html).
> 
> What do you think?

I didn't though this would be so much difficult, in fact exporting `exports` and `memory` would be trivial, and it's just `memory` the one that would not allow to export directly `exports` content and make it more pythonic, but being `memory` something that can be exported too then it makes sense from an API perspective. Anyway, I always advocate for clean, simple and intuitive APIs following the idioms of each particular language, and if this means a refactor is needed (I don't think so) to make it more pythonic, then I would go for it.

**Comment by Mec-iS** [comment]
> Are these two files? What's BYTES?
```
from wasmer import Load  # or LoadInstance

module = Load(WASM_BYTES)  # Load takes compiled WASM file as bytes, instead of using Instance

from module import func
...
This way we have the first loading step returning a module, from which functions can be imported instead of being just called using `intsance.exports`

> Dynamically added sub-modules?
I don't understand what you mean with dynamically added as Rust is a compiled language, at most we can add them programmatically

**Comment by Hywan** [comment]
Just a side note: I'm OK to break the API, we are still on the 0.y.z branch.

**Comment by piranna** [comment]
> ```python
> from wasmer import Instance
> module = Instance(BYTES).load()
> ```

I still don't see about having direct access to `Instance` or `BYTES`, they should be implementation details, the ideal is people would only need to do `from module import func_name`, not having a clear distinction between Python modules or WebAssembly based ones... How much frequently will people use `memory`? If not so much, maybe we can expose just only exported functions and left `memory` as an advanced feature that requires you access directly to the Wasmer APIs, because I'm not sure if there's some equivalent in Python that people would use so much besides `StringIO`...

**Comment by Mec-iS** [comment]
we should start a list of requirements for a 1.0 interface. Where we can discuss? I am in wasmer's Spectrum chat, for the meanwhile I started a gist, please comment: https://gist.github.com/Mec-iS/7ac190d7b46dad71e4a5691eb70e5ab9

**Comment by Mec-iS** [comment]
@piranna can you try the new interface implemented in PRs #47 and #48 and let us know what you think?

**Comment by Hywan** [comment]
Another “more magical” idea (less hackable though) is the following:

```py
from my_program import sum
```

which is equivalent to write:

```py
instance = Instance("my_program.wasm")
sum = instance.exports.sum
```

Pro:

* Fully transparent for the user, no “Wasm involved” at any step

Con:

* Less hackable. Too much magic. But `Instance` & co. is still accessible for more specific workflow,
* How to support imported functions with this method? I think it's not possible without too much magic.

I know [`wasmtime-py` is doing this](https://github.com/CraneStation/wasmtime/blob/8b5b22599f77bde85067b7314743f367c4038a3d/misc/wasmtime-py/python/wasmtime/__init__.py). I don't know what to think about it.

**Comment by Mec-iS** [comment]
we may want to consider also a more tool-based approach. what about something like a `piprust` command with this workflow:
* the developer creates a Rust crate for his/her dynamic lib i.e. called `jumper`
* in the crate root she/he run `piprust jumper` and a Python package is created in the crate with everything needed
* the developer move the newly created `jumper` directory into his/her Python project so to do ` from jumper import external_func`
this would ease things more than any improvement in the interface imo.

**Comment by filips123** [comment]
@Mec-iS But you would have to run this at any change. It would be better to dynamically generate that "wrapper". Also, it would be hard to create a tool for each possible language.

**Comment by Mec-iS** [comment]
> But you would have to run this at any change

that is already true as any change in Rust code should be built for wasm32

> it would be hard to create a tool for each possible language

again, this is what we are already doing, any language has its own wasmer package.

**Comment by Hywan** [comment]
Do you think it is still valuable? I don't think that's a path to follow anymore.

**Comment by Hywan** [comment]
Closing the issue. Feel free to reopen if necessary :-).
