### ISSUE TITLE
Are there plans to release for Python 3.9 ?

### ISSUE THREAD

**Issue by jacopofar** [wasmerio/wasmer-python#407]
### Summary

Currently installing the package with Python 3.9 on macOS doesn't give errors but actually only installs an `__init__,py` with:

    raise ImportError("Wasmer is not available on this system")

now that Python 3.9 is released as stable, is there a roadmap to release for it?

**Comment by syrusakbary** [comment]
Yes, we plan to support Python 3.9... stay tuned!

**Comment by Hywan** [comment]
The next release will produce wheels for Python 3.9 :-).
