### ISSUE TITLE
Documentation and user experience

### ISSUE THREAD

**Issue by Mec-iS** [wasmerio/wasmer-python#44]
### Motivation
The library needs some documents to guide developers through adoption/usage/contribution, so to bring them to a "what to do next" stage after trying the example in the README.

### Proposed solution
We are working out some stuff in a [section of this gist](https://gist.github.com/Mec-iS/7ac190d7b46dad71e4a5691eb70e5ab9#guideines-to-adoptioncontribution). Please leave this issue open to track progress.

### Additional context

It would be great in the future to have an online playground where user can load their own WASM-compiled binary and then try some scripting in Python in an interactive way (like [Skulpt](http://www.skulpt.org/))

**Comment by Hywan** [comment]
Those are good ideas.

What's the idiomatic tool to write documentation for Python?

**Comment by Mec-iS** [comment]
I think the most used is [`autodoc` based on Python Sphinx](http://www.sphinx-doc.org/en/master/), it is a docstrings processor based on reStructuredText directives. A lot of third-parties packages are hosted on https://readthedocs.org/

**Comment by Mec-iS** [comment]
NOTE: I see a lot of related things going on at github/RustPython like https://rustpython.github.io/demo/

**Comment by Mec-iS** [comment]
I am collecting as much examples in one of my repo, when they will reach a proper shape I will probably propose a PR to create a `docs` directory.

**Comment by Hywan** [comment]
Thank you. Tell me how I can help you, I've time for it.

**Comment by Mec-iS** [comment]
I am collecting examples and  a sort of walkthrough https://github.com/Mec-iS/rust-wasm-python-101/tree/master/pywasm

**Comment by Mec-iS** [comment]
Note: it would be nice to have [WebAssembly Studio](https://webassembly.studio) mentioned in the README with few words to make new users visualise how a Rust function can be compiled to Wasm.

**Comment by Hywan** [comment]
There is now a beautiful documentation generated by pdoc3, https://wasmerio.github.io/wasmer-python/api/.
