### ISSUE TITLE
Roadmap to v1.0 interface

### ISSUE THREAD

**Issue by Mec-iS** [wasmerio/wasmer-python#45]
### Motivation

As proposed in #37, it would be nice to collect ideas about how a stable interface should look like from the Python side and how to make it possible using the latest additions to `pyo3`.

### Proposed solution

Collecting notes and comments in [this gist](https://gist.github.com/Mec-iS/7ac190d7b46dad71e4a5691eb70e5ab9#ideas-for-a-stable-interface). Please keep this issue open to keep track of progress.

**Comment by Mec-iS** [comment]
#47 #48

**Comment by Mec-iS** [comment]
#68

**Comment by Hywan** [comment]
The 1.0.0 version has been released, https://github.com/wasmerio/wasmer-python/releases/tag/1.0.0, closing this issue :-).
