### ISSUE TITLE
Type signature for i64

### ISSUE THREAD

**Issue by prescod** [wasmerio/wasmer-python#452]
Thanks for proposing a new feature!

### Motivation

I need to create the type signature for a function returning i64. I am auto-generating code for these functions so its very inconvenient to treat i64 specially.

### Proposed solution

def HPyLong_AsLongLong(runtime_context, ctx: int, num_handle: int) -> Value.i64:

AND

def HPyLong_AsLongLong(runtime_context, ctx: int, num_handle: int) -> Type.I64:

Should both do it.

### Additional context

Also:

def returns_nothing() -> None

should be treated identically to:

def returns_nothing()

As it is in the rest of Python.

**Comment by Hywan** [comment]
Hello,

You can type your arguments and result with `'i64'` already:

https://github.com/wasmerio/wasmer-python/blob/198b5a81b73a6d448beb8cca5176e39ad5dd2522/packages/api/src/externals/function.rs#L115-L118

We could support `None` as nothing, yes, I think it's doable.

If the question about `i64` is resolved, please let me know, I'll rename the issue consequently.

**Comment by prescod** [comment]
Hellow HyWan. This test raises an inference-failure exception for all four functions with wasmer 1.0.0b1 :

```
from wasmer_compiler_cranelift import Compiler
from wasmer import engine, Store, Module, Instance, Type, Value, ImportObject, Function

store = Store(engine.JIT(Compiler))
import_object = ImportObject()

def func(f):
    try:
        return Function(store, f)
    except Exception as e:
        print(e)

def divmod(x: int, y: int) -> (int, int):
    return (x // y, y % x)

func(divmod)

def bigadd(x: int, y: int) -> Type.I64:
    return x + y
func(bigadd)


def bigaddV(x: int, y: int) -> Value.i64:
    return x + y
func(bigaddV)


def Nothing(x: int, y: int) -> None:
    return None
func(Nothing)

```

**Comment by Hywan** [comment]
In #537, the accepted annotations have been documented. The `None` type-hint is now accepted in `return` position.

Thanks for the issue!
