### ISSUE TITLE
Potential memory bug for memory.buffer

### ISSUE THREAD

**Issue by chmp** [wasmerio/wasmer-python#498]
Not sure this really is an issue in practice, but I still wanted to raise it. At the moment wasmer does not set the owner pointer of the buffer view (`obj`, [relevant location](https://github.com/wasmerio/wasmer-python/blob/953a17ad7666ea623a7b08419e347a76ec9107e7/packages/api/src/memory/buffer.rs#L100)). 

My understanding is that in principle this could lead to invalid memory access, if the buffer outlives the reference to the wasmer objects it was created from. In practice this should be a non issue as numpy, and I belief also memoryview, explictly retrain a reference to the object used to get the buffer view. However, this additional saftey is not required by Python and therefore different consumers of the buffer view may encounter memory bugs.

To correctly track the owner of the memory, it should be enough to change the [linked line](https://github.com/wasmerio/wasmer-python/blob/953a17ad7666ea623a7b08419e347a76ec9107e7/packages/api/src/memory/buffer.rs#L100) to

```rust
use pyo3::ffi::Py_IncRef;

(*view).obj = slf.as_ptr();
Py_IncRef((*view).obj);
```

This change would follow the [documented buffer protocol](https://docs.python.org/3.9/c-api/typeobj.html#c.PyBufferProcs.bf_getbuffer): "Set view->obj to exporter and increment view->obj." No change of the release method is required, as Python will decrement the ref count according to the [docs](https://docs.python.org/3.9/c-api/typeobj.html#c.PyBufferProcs.bf_releasebuffer).

A small caveat: I only started to look into the buffer protocol recently, so there is a good chance I misunderstood some of the contracts involved :).

**Comment by Hywan** [comment]
Hello,

Thanks for the detailed issue :-)! Spoiler: I'm not _super_ familiar with the Buffer Protocol neither. Are you willing to open a PR to try this out? I reckon your solution is relevant.

**Comment by chmp** [comment]
Sure. Happy to. I'll give a try now.

**Comment by chmp** [comment]
While playing around with ctypes in the hope of forcing the suspected memory error, I ran into a second issue. At the moment the `readonly` flag is set depending on the request. However, this clashes with the way the ctypes modules uses the buffer interface:

1. They use [PyMemoryView_FromObject](https://github.com/python/cpython/blob/d96a7a83133250377219227b5cfab4dbdddc5d3a/Modules/_ctypes/_ctypes.c#L615)
2. It in turn uses [PyObject_GetBuffer](https://github.com/python/cpython/blob/63298930fb531ba2bb4f23bc3b915dbf1e17e9e1/Objects/memoryobject.c#L104) with read or write access
3. Ctypes [checks explictly](https://github.com/python/cpython/blob/d96a7a83133250377219227b5cfab4dbdddc5d3a/Modules/_ctypes/_ctypes.c#L621), whether the buffer is writeable 

I think this expectation of the ctypes modul eis consistent with the [documented contract](https://docs.python.org/3.8/c-api/buffer.html#c.PyBUF_WRITABLE):

> **PyBUF_WRITABLE**
> Controls the readonly field. If set, the exporter MUST provide a writable buffer or else report failure. Otherwise, the exporter MAY provide either a read-only or writable buffer, but the choice MUST be consistent for all consumers.

If you read the way that the choice must be consistent regardles of the flag, i.e., the buffers must be always readonly or writable, then it matches the observed behavior by ctypes.

In any case, I would also make the buffer always writable, as it should be compatible with the interface that wasmer provides.

<details>
Ctypes use to cause the error:

```python
> array_type = ctypes.c_uint8 * 1000
> a = array_type.from_buffer(mod.__memory__.buffer)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-4d452f0fe07f> in <module>
      1 array_type = ctypes.c_uint8 * 1000
----> 2 a = array_type.from_buffer(mod.__memory__.buffer)

TypeError: underlying buffer is not writable
```
</details>

**Comment by chmp** [comment]
Opened the PR. The tests run locally.

**Comment by Hywan** [comment]
Let's discuss about the PR in the PR's thread directly. Thank you very much for the deep look and the argued comments!
