### ISSUE TITLE
Can we have an example for Pytorch running with reactjs or nodejs as an example?

### ISSUE THREAD

**Issue by JonathanSum** [wasmerio/wasmer-python#508]
### Summary

Can we have an example for Pytorch running with reactjs or nodejs as an example?

### Additional details

pip3 install torch==1.8.1+cu102 torchvision==0.9.1+cu102 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by Hywan** [comment]
Hello,

Pytorch is a Python project, written in C++ as a Python extension, for what I know about the project. How is it related to WebAssembly? `wasmer-python` is a WebAssembly runtime for Python.

Also, I don't understand the:

> running with reactjs or nodejs

`wasmer-python` doesn't compile Python to WebAssembly. It executes WebAssembly _inside_ Python.

:-)

**Comment by JonathanSum** [comment]
Sorry. I was asking to executes Pytorch code in Javascript.

**Comment by Hywan** [comment]
Then it's not the place to get help. I'm not maintaining Pytorch, and this project isn't about JavaScript :-). I'm closing the issue. You can open an issue directly on the Pytorch project, https://github.com/pytorch/pytorch.
