### ISSUE TITLE
RFE: Support `-> None` function annotations

### ISSUE THREAD

**Issue by FGasper** [wasmerio/wasmer-python#534]
### Motivation

@syrusakbary asked me to open this. :)

(https://wasmerians.slack.com/archives/C01M492T9A9/p1626106300005600)

### Proposed solution

I’d like wasmer-python to be able to infer an empty return from `None` as the return type, e.g.:
```
def abort_fn(a: int, b: int, c: int, d: int) -> None:
```
Right now it fails thus:
```
TypeError: `ImportObject` cannot register the given type `Ok("function")`
```

### Alternatives

Right now you have to create a Function() to import a no-return host function, which is clunky.

**Comment by Hywan** [comment]
Hello,

A function cannot return “None”, but it can return nothing:

```py
def abort_fn(a: int, b: int, c: int, d: int):
```

It works the same.

**Comment by FGasper** [comment]
Ahh ok.

Apologies for the “noise”; I’m better with Perl and C. :)

**Comment by FGasper** [comment]
@Hywan Would you accept a PR that demonstrates that usage?

**Comment by Hywan** [comment]
I've open a PR (#537) to accept this type-hint as it seems usual. I've also updated the documentation to explain all the accepted annotations and how they map to WebAssembly.
