### ISSUE TITLE
wasmer-python raises an error when reading multi-modules WASM

### ISSUE THREAD

**Issue by millicent-admin** [wasmerio/wasmer-python#600]
### Bug description 

I am using wasmer-python to read the wasm file of https://github.com/docknetwork/crypto-wasm. The issue is that all the examples available in wasmer-python read a wasm file which contains one module. In crypto-wasm we have several modules and I suspect that this is the issue in the following code. 

### Steps to reproduce

Here is the python code:

```
from wasmer import engine, Store, Module, Instance
from wasmer_compiler_cranelift import Compiler

engine = engine.Universal(Compiler)

# Let's define the store, that holds the engine, that holds the compiler.
store = Store(engine)

# Let's compile the module to be able to execute it!
module = Module(store, open('wasm.wasm', 'rb').read())

# Now the module is compiled, we can instantiate it.
instance = Instance(module)
```

Then `wasm.wasm` file is the file generated when running the command `yard build` for the repo https://github.com/docknetwork/crypto-wasm.

### Expected behavior

I should be able to read the wasm file and call its functions without errors.
### Actual behavior

I get the following error:

```
zak@ubuntu:~/accumulator/python-server$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    instance = Instance(module)
RuntimeError: Error while importing "__wbindgen_placeholder__"."__wbindgen_object_drop_ref": unknown import. Expected Function(FunctionType { params: [I32], results: [] })
```

**Comment by Amanieu** [comment]
Wasmer doesn't support the module linking proposal for WASM. However you might be able to link these into a single module using [wasmlink](https://github.com/bytecodealliance/wit-bindgen/tree/main/crates/wasmlink).

**Comment by syrusakbary** [comment]
Hi, we got a bit confused by the "multi-modules" statement.
The thing is not whether that module-linking is supported, as your project is using wasm-bindgen trying to target the browser (and module linking is just a draft, with no support from any browser Wasm runtime).

It seems the main issue is that the required imports that the generated wasm module has are not provided. You can try to rewrite the imports from js (the language that wasm-bindgen outputs to) to python and use it with python.
@millicent-admin
