### ISSUE TITLE
No module named 'wasmer' after " pip install wasmer wasmer_compiler_cranelift" on Ubuntu 20.04

### ISSUE THREAD

**Issue by AliceNZ** [wasmerio/wasmer-python#611]
### Summary
$ pip install wasmer wasmer_compiler_cranelift
Collecting wasmer
  Downloading wasmer-1.1.0-cp39-cp39-manylinux_2_24_x86_64.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 1.8 MB/s 
Collecting wasmer_compiler_cranelift
  Downloading wasmer_compiler_cranelift-1.1.0-cp39-cp39-manylinux_2_24_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 8.5 MB/s 
Installing collected packages: wasmer-compiler-cranelift, wasmer
Successfully installed wasmer-1.1.0 wasmer-compiler-cranelift-1.1.0

$ python -c 'from wasmer import engine'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'wasmer' — current issue

$ which python
~/anaconda3/bin/python

$ python --version
Python 3.9.10

OS: Ubuntu 20.04 LTS 64-BIT
### Additional details

I see there is an open issue on Windows with similar problem here: 
https://github.com/wasmerio/wasmer-python/issues/539

**Comment by syrusakbary** [comment]
This is quite weird. The linked issue #539 is related to Wasmer not being available in your system (a default package is installed).

I assume this have something to do more related to your anaconda system. Are you able to install and import other packages properly?

**Comment by AliceNZ** [comment]
Thank you for your answer. You are right, I tried numpy, which also failed though numpy was installed.
$ pip install numpy
Requirement already satisfied: numpy in ~/anaconda3/lib/python3.9/site-packages (1.20.3)
$ sudo python -c 'import numpy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'

The reason is the pip installed path is not in the site package path:
$ python -c "import site; print(site.getsitepackages())"
['/usr/local/lib/python3.9/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.9/dist-packages']

Thanks again, BTW, do you have any update on the 3-year-old Pyodide wasm package? It did not work. I encountered same error as the thread here: https://github.com/wapm-packages/pyodide/issues/1

**Comment by syrusakbary** [comment]
We have a custom Python implementation that is pure wasm, you can find it here:

https://github.com/wapm-packages/cpython
