### ISSUE TITLE
RuntimeError: Compilation error: The UniversalEngine is operating in headless mode, so it can only execute already compiled Modules.

### ISSUE THREAD

**Issue by kenorb** [wasmerio/wasmer-python#645]
### Summary

I've compiled my C++ program with:

    emcc -s ERROR_ON_UNDEFINED_SYMBOLS=0 -g App.cpp -o App.wasm

But when trying the following code from examples:

```
from wasmer import Store, Module, Instance, Memory
module = Module(Store(), open('App.wasm', 'rb').read())
```

I've got the following error:

> RuntimeError: Compilation error: The UniversalEngine is operating in headless mode, so it can only execute already compiled Modules.

The message is confusing, as my .wasm file is already compiled (binary format). I've used it successfully using Javascript.

Can I still use it somehow or need to compile it in a different way?

I'm using wasmer 1.1.0 with Python 3.

**Comment by syrusakbary** [comment]
Hi @kenorb, it seems you need to install `wasmer_compiler_cranelift` (or `wasmer_compiler_singlepass`) and things will be automatically fixed.

Let me know if that works for you!

**Comment by kenorb** [comment]
Works after installing the package,  thanks.
